#!/usr/bin/sh
#
# Organization: MDIBL
# Author: Lucie Hutchins
# Date: August 2017
#
#A simple script that downloads and stores locally the cuurent release
# number of Ensembl database
#
# What it does:
#  1) downloads the current release Readme file
#  2) sets the current release number flag
#
# This will be scheduled on Jenkins to run dailly
#
cd `dirname $0`

SCRIPT_NAME=`basename $0`
WORKING_DIR=`pwd`
release_readme_config="ensembl/ftp.ensembl.org.current_readme.cfg"

if [ ! -f ../Configuration ]
then
  echo "'Configuration' file missing "     
  exit 1
fi
if [ ! -f ensembl.cfg ]
then
  echo "'ensembl.cfg' file missing under $WORKING_DIR"     
  exit 1
fi

source ../Configuration
source ./ensembl.cfg

ENSEMBL_BASE="$EXTERNAL_DATA_BASE/$SHORT_NAME"
#setup the log
LOG_FILE="${DOWNLOADS_LOG_DIR}/$SCRIPT_NAME.log"
rm -rf $LOG_FILE
touch $LOG_FILE

date | tee -a $LOG_FILE
echo "**********              *******************" | tee -a $LOG_FILE
echo " Checking Ensembl Current Release Number"| tee -a $LOG_FILE
echo "**********  *******************************"| tee -a $LOG_FILE
echo ""| tee -a $LOG_FILE
echo " LOGS"| tee -a $LOG_FILE
echo "Logs generated by this script are under ${DOWNLOADS_LOG_DIR}"| tee -a $LOG_FILE
echo "Log: $SCRIPT_NAME.log"| tee -a $LOG_FILE
echo "Log: ftp.ensembl.org.current_readme.cfg.log"| tee -a $LOG_FILE
echo ""| tee -a $LOG_FILE
echo " FILES"| tee -a $LOG_FILE
echo "Files generated by this script are under ${ENSEMBL_BASE}"| tee -a $LOG_FILE
echo "File: current_README"| tee -a $LOG_FILE


./../download_package $release_readme_config

if [ ! -f ${ENSEMBL_BASE}/current_README ]
then
   echo "Download failed: ${ENSEMBL_BASE}/current_README is missing" 
   exit 1
fi

RELEASE_NUMBER=`head ${ENSEMBL_BASE}/current_README | grep "Ensembl Release" |sed 's/Databases.//'|sed 's/Ensembl Release //'`
## Create the current release Number file
release_flag=${ENSEMBL_BASE}/current_release_NUMBER.$RELEASE_NUMBER
touch $release_flag

echo "Current Release Number:$RELEASE_NUMBER"| tee -a $LOG_FILE
echo ""| tee -a $LOG_FILE
echo "Program complete"| tee -a $LOG_FILE


echo "********** System dump *******************"| tee -a $LOG_FILE
echo " ENVIRONMENT VARIABLES DUMP"| tee -a $LOG_FILE
echo "**********  *******************************"| tee -a $LOG_FILE
env | sort | tee -a $LOG_FILE
exit 0
